apiVersion: v1
kind: Service
metadata:
  name: memo-app
  namespace: memo-prod
spec:
  selector:
    app: memo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181
  type: LoadBalancer
